version: '3.9'
services:
  starter-service:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
        - starter-network
    environment:
      - ServiceName=backend-service
      - OTEL_EXPORTER_JAEGER_AGENT_HOST=jaeger
      - OTEL_EXPORTER_JAEGER_AGENT_PORT=6831
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - otel-collector
      - postgres
      - keycloak

  postgres:
    image: postgres:14.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
        - starter-network
    volumes:
      - starter-sqldata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports: 
      - 7001:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    networks:
      - starter-network
    volumes:
      - keycloak-data:/opt/keycloak/data
    command:
      - "start-dev"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    command: --config /etc/otelcol/otel-collector-config.yml
    volumes:
      - ./Configs/otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml
    ports:
      - 4317:4317
      - 8888:8888
      - 8889:8889
    networks:
      - starter-network
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.52
    command: --query.ui-config=/etc/jaeger/jaeger-ui.json --collector.otlp.enabled=true --prometheus.server-url=http://prometheus:9090 --prometheus.query.support-spanmetrics-connector=true
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
    volumes:
      - ./Configs/jaeger-ui.json:/etc/jaeger/jaeger-ui.json
    ports:
      - 16686:16686
    networks:
      - starter-network
 
  prometheus:
    image: prom/prometheus:v2.48.1
    volumes:
      - ./Configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - 9090:9090
    networks:
      - starter-network
  
  loki:
    image: grafana/loki:2.9.3
    command: -config.file=/mnt/config/loki-config.yml
    volumes:
      - ./Configs/loki.yml:/mnt/config/loki-config.yml
      - loki-data:/loki
    ports:
      - 3100:3100
    networks:
      - starter-network
  
  grafana:
    image: grafana/grafana:10.2.3
    volumes:
      - ./Configs/grafana.ini:/etc/grafana/grafana.ini
      - ./Configs/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./Configs/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./Configs/dotnet-otel-dashboard.json:/etc/grafana/provisioning/dashboards/dotnet-otel-dashboard.json
      - ./Configs/aspnet-core-dahsboard.json:/etc/grafana/provisioning/dashboards/aspnet-core-dahsboard.json
      - ./Configs/node-exporter-dashboard.json:/etc/grafana/provisioning/dashboards/node-exporter-dashboard.json
      - ./Configs/logs-dashboard.json:/etc/grafana/provisioning/dashboards/logs-dashboard.json
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - starter-network

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.5.0
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - starter-network

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
    ports:
      - 3001:3001
    networks:
      - starter-network
    restart: always

volumes:
  starter-sqldata:
  grafana-data:
  prometheus-data:
  uptime-kuma-data:
  loki-data:
  keycloak-data:
      driver: local

networks:
  starter-network:
    driver: bridge

